CREATE TABLE transactions (
user_id TEXT NOT NULL, stock TEXT NOT NULL,
symbol TEXT NOT NULL,
price NUMERIC NOT NULL,
shares INTEGER NOT NULL,
type TEXT NOT NULL,
time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(user_id) REFERENCES users(id)
);